FROM apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu

WORKDIR /app

COPY pyspark_consumer.py /app/pyspark_consumer.py

USER root
RUN pip install pyspark

# CMD ["python3", "/app/pyspark_consumer.py", "--capture-all"]

ENTRYPOINT ["/opt/spark/bin/spark-submit", \
     "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.13:4.0.1", \
     "/app/pyspark_consumer.py"]
